### ISSUE TITLE
Problemi meccanico

### ISSUE THREAD

**Issue by Timo43** [ProjectHorizonRP/public_issues#191]
Id: Phant0m43

- [x] Il camion per trasporto veicoli moddato del meccanico non viene rilevato dal comando Tow (devi prima entrare in un carro attrezzi), 
- [x] Il comando tow non funziona ( veicolo non viene rilevato ) e non da errori in console, 
- [x] veicolo Chevrolet Camarro non si possono fare le modifiche al motore perché non da il comando dell'azione. 
- [x] Non si possono fare modifiche alle moto riguardanti gomme e sospensioni perché rileva come se fossero dei veicoli e se riapri il menu dice che sei ancora nella fase di riparazione. 
- [x] Dal menu del direttore non si può direttamente prelevare il denaro dalla banca (quantità non valida)
